// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0-k5EL5VtuNigj-RWKpF-fKK8jzwfBms',
    appId: '1:362569442877:web:7573f611f7533049b8ac54',
    messagingSenderId: '362569442877',
    projectId: 'kaidaow-wireless',
    authDomain: 'kaidaow-wireless.firebaseapp.com',
    storageBucket: 'kaidaow-wireless.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4d7dB7H4LdtnV25-B6YBue-VE-YzkkuQ',
    appId: '1:362569442877:android:4cf2bf6e31661589b8ac54',
    messagingSenderId: '362569442877',
    projectId: 'kaidaow-wireless',
    storageBucket: 'kaidaow-wireless.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA2ANQnojFa-SK9_EGHU5UcvID3Cwg-a4',
    appId: '1:362569442877:ios:d9d03a904631d040b8ac54',
    messagingSenderId: '362569442877',
    projectId: 'kaidaow-wireless',
    storageBucket: 'kaidaow-wireless.appspot.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA2ANQnojFa-SK9_EGHU5UcvID3Cwg-a4',
    appId: '1:362569442877:ios:5ccca9e4250388e5b8ac54',
    messagingSenderId: '362569442877',
    projectId: 'kaidaow-wireless',
    storageBucket: 'kaidaow-wireless.appspot.com',
    iosBundleId: 'com.example.application.RunnerTests',
  );
}
